CREATE TABLE sqlite_sequence(
	name,
	seq
);



CREATE TABLE ETUDIANT (
	ID_ETUDIANT INTEGER PRIMARY KEY AUTOINCREMENT ,
	NOM_ETUDIANT VARCHAR(50) ,
	PRENOM_ETUDIANT VARCHAR(50),
	NOM_ETUDIANT_ARABE VARCHAR(50),
	PRENOM_ETUDIANT_ARABE VARCHAR(50),
	DATE_NAISSANCE_ETUDIANT date,
	ADRESSE_ETUDIANT varchar(255),
	VILLE_ETUDIANT varchar(50),
	TEL_ETUDIANT varchar(11),
	DATE_ELIGIBILITE_ETUDIANT date,
	DATE_ADMISSION_ETUDIANT date,
	CIN_ETUDIANT VARCHAR(11) UNIQUE,
	CNE_ETUDIANT VARCHAR(11) UNIQUE,
	EMAIL_ETUDIANT VARCHAR(50),
	REVENU_DES_PARENTS float,
	NOMBRE_DES_FRERES_SOEURS int,
	NIVEAU_ETUDE VARCHAR(50),
	ETAT_ETUDIANT VARCHAR(50) ,
	N_DOSSIER VARCHAR(30) UNIQUE, 
	CHAMBRE VARCHAR(50), 
	PAVILLON VARCHAR(50), 
	DATE_DEBUT DATE, 
	DATE_FIN DATE, 
	SOMME FLOAT, 
	DISTANCE FLOAT, 
	CONDITION_SPECIAL BOOLEAN DEFAULT false, 
	SEXE_ETUDIANT VARCHAR(20), 
	ANCIENNETE VARCHAR(50), 
	COMPORTEMENT VARCHAR(50), 
	ETABLISMENT VARCHAR(50), 
	DIPLOME VARCHAR(50), 
	REMARQUE TEXT, 
	PASSPORT VARCHAR(50) UNIQUE, 
	CARTE_SEJOUR VARCHAR(50) UNIQUE, 
	PAYS VARCHAR(50), 
	EXCELLENCE VARCHAR(50)
);



CREATE TABLE CHAMBRE (ID_CHAMBRE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	PAVILLON VARCHAR(50), 
	NOM_CHAMBRE VARCHAR(50), 
	CAPACITE INTEGER, 
	LIBRE INTEGER ,
	ETAGE VARCHAR(50), 
	TYPE VARCHAR(50)
);



CREATE TABLE DEPOT (
	ID_DEPOT INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	DATE_DEPOT DATE,
	N_DOSSIER VARCHAR(50),
	NOM_ETUDIANT VARCHAR(50),
	PRENOM_ETUDIANT VARCHAR(50),
	CNE VARCHAR(50),
    CIN VARCHAR(50)
);



CREATE TABLE PAIEMENT (
	ID_PAY INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	N_DOSSIER VARCHAR(50),
	NOM_ETUDIANT VARCHAR(50), 
	PRENOM_ETUDIANT VARCHAR(50), 
	CIN VARCHAR(50), 
	CNE VARCHAR(50), 
	DATE_PAY DATE, 
	MONTANT FLOAT
);



CREATE TABLE PAVILLON (
	ID_PAVILLON INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	PAVILLON VARCHAR(50),
	NOMBRE_ETAGE INTEGER,
	TYPE VARCHAR(50)
);



CREATE TABLE REFERENTIEL (
	ID_REF INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
 	VILLE VARCHAR(50), 
 	NOM VARCHAR(50), 
 	PLACE_ETRANGER INTEGER, 
 	PLACE_ANCIEN INTEGER
);



CREATE TABLE RESERVATION (
	ID_RESERVATION INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	DATE_RESERVATION DATE, 
	CHAMBRE VARCHAR(50), 
	PAVILLON VARCHAR(50), 
	ID_ETUDIANT INTEGER
);